apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nextcloud-autoconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud-helmchart.labels" . | nindent 4 }}
data:
  collabora.config.php: |
    <?php
    $CONFIG = [
      'richdocuments' => [
        'enabled' => 'yes',
        'wopi_url' => 'https://{{ .Values.domain.collabora | default .Values.collabora.domain }}',
        'wopi_allowlist' => '10.0.0.0/8,127.0.0.1',
      ],
      'allow_local_remote_servers' => true,
    ];
