apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-session-ini
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud-helmchart.labels" . | nindent 4 }}
data:
  session.ini: |
    session.save_handler = redis
    {{- if .Values.redis.auth.enabled }}
    session.save_path = "tcp://{{ .Release.Name }}-redis-master:6379?auth={{ .Values.redis.auth.password | default "RedisPassword@1234" | urlquery }}"
    {{- else }}
    session.save_path = "tcp://{{ .Release.Name }}-redis-master:6379"
    {{- end }}
