apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-admin-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud-helmchart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-admin-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud-helmchart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-admin-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud-helmchart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-admin-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-admin-role
  apiGroup: rbac.authorization.k8s.io
