apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-system

helmCharts:
  - name: nextcloud-helmchart
    releaseName: nextcloud
    namespace: nextcloud-system
    version: 1.0.0
    repo: file://../../charts/nextcloud-helmchart
    valuesFile: ../../charts/nextcloud-helmchart/values.yaml
