apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-dev

resources:
  - ../../base

helmCharts:
  - name: nextcloud-helmchart
    releaseName: nextcloud-dev
    namespace: nextcloud-dev
    version: 1.0.0
    repo: https://PorKeat.github.io/nextcloud-helm-chart/
    valuesFile: custom-values.yaml
